/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import Cursos.R_Estudiante;


/**
 *
 * @author Pablito Garzona
 */
public class Estudiantes extends javax.swing.JInternalFrame {

    private static Estudiantes est = null;
    private R_Estudiante estudiante;

    /**
     * Creates new form Estudiantes
     */
    private Estudiantes() {
        initComponents();
    }

    public static Estudiantes getEst() {
        if (est == null) {
            est = new Estudiantes();
        }
        return est;

    }
    
    public R_Estudiante getEstudiante(){
        return estudiante;
    }
    
    public void setEstudiante (R_Estudiante estudiante){
        this.estudiante=estudiante;
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
