/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NotasS.Catedratico;

import Conexion.ConexionJPA;
import NotasS.ListaSecCurso_EstuSec_EntAct;
import com.sun.java.accessibility.util.AWTEventMonitor;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Query;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;

/**
 *
 * @author Saul
 */
public class Estudiante extends javax.swing.JInternalFrame {

    public List<ListaSecCurso_EstuSec_EntAct> miLista;
    public int usuarioEstId;
    public String carneEst;
    public int entId;
    ListSelectionModel seleccionEst;
    /**
     * Creates new form Estudiante
     */
    public Estudiante() {
        initComponents(); 
    }
    
    public Estudiante(List<ListaSecCurso_EstuSec_EntAct> miListaSecCurs_EstuSec_EntrActi, int UsuarioEstId, String carneEst) {
        initComponents();
        this.miLista = miListaSecCurs_EstuSec_EntrActi;
        this.usuarioEstId = UsuarioEstId;  
        this.carneEst = carneEst;
        cargarDatos();
        deshabilitarBotones();
        esconderColumna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaNotas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCarne = new javax.swing.JTextField();
        jTextFieldCurso = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNotaTotal = new javax.swing.JTextField();
        jButtonCalificacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCalificacion = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TablaNotas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        seleccionEst = TablaNotas.getSelectionModel();
        seleccionEst.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if(! e.getValueIsAdjusting()){
                    tablaNotaSeleccion(TablaNotas);
                }

            }
        });

        TablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Actividad", "Titulo", "FechaEntrega", "FechaPublicacion", "Valoracion", "ActividadFisica", "ActividadVirtual", "Engrega", "Calificacion", "EntregaId"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaNotas);
        if (TablaNotas.getColumnModel().getColumnCount() > 0) {
            TablaNotas.getColumnModel().getColumn(0).setResizable(false);
            TablaNotas.getColumnModel().getColumn(1).setResizable(false);
            TablaNotas.getColumnModel().getColumn(2).setResizable(false);
            TablaNotas.getColumnModel().getColumn(3).setResizable(false);
            TablaNotas.getColumnModel().getColumn(4).setResizable(false);
            TablaNotas.getColumnModel().getColumn(5).setResizable(false);
            TablaNotas.getColumnModel().getColumn(6).setResizable(false);
            TablaNotas.getColumnModel().getColumn(7).setResizable(false);
            TablaNotas.getColumnModel().getColumn(8).setResizable(false);
            TablaNotas.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setText("ESTUDIANTE");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Curso:");

        jLabel5.setText("Carne:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setText("Nota total:");

        jButtonCalificacion.setText("Actualizar calificacion");
        jButtonCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificacionActionPerformed(evt);
            }
        });

        jLabel7.setText("Titulo:");

        jLabel8.setText("Calificacion:");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNotaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonCalificacion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNotaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        ListaEstudiantes miLis = new ListaEstudiantes();
        Principal.jDesktopPane1.add(miLis);
        miLis.show();
        try {
            miLis.setMaximum(Boolean.TRUE);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Estudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificacionActionPerformed
        // TODO add your handling code here:
        Double calificacion = Double.parseDouble(this.jTextFieldCalificacion.getText());
        Query query = ConexionJPA.getInstance("usuario", "usuario").getEm().createQuery(
        "UPDATE Entrega e SET e.calificacion = " + calificacion + "" +
        "WHERE c.id = :entregaId ");
        int updateCount = query.setParameter("entregaId", entId).executeUpdate();
        this.repaint();
    }//GEN-LAST:event_jButtonCalificacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaNotas;
    private javax.swing.JButton jButtonCalificacion;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCalificacion;
    private javax.swing.JTextField jTextFieldCarne;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNotaTotal;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        
        DefaultTableModel miTablaNotas = (DefaultTableModel) TablaNotas.getModel();
        int cont = 0;
        Iterator<ListaSecCurso_EstuSec_EntAct> iteradorLisSecCur_EstuSec_EntAct = miLista.iterator();
        while (iteradorLisSecCur_EstuSec_EntAct.hasNext()) { 
            ListaSecCurso_EstuSec_EntAct ListaSecCur_EstSec_EntAct = iteradorLisSecCur_EstuSec_EntAct.next();
            
            if (ListaSecCur_EstSec_EntAct.getUsuarioEstId() == usuarioEstId) {
                if (cont == 0) {
                    this.jTextFieldApellido.setText(ListaSecCur_EstSec_EntAct.getApellidoEst());
                    this.jTextFieldCarne.setText(carneEst);
                    this.jTextFieldCurso.setText(ListaSecCur_EstSec_EntAct.getCurso());
                    this.jTextFieldNombre.setText(ListaSecCur_EstSec_EntAct.getNombreEst());
                }
                
                if (ListaSecCur_EstSec_EntAct.getEntregaRealizada() == Boolean.TRUE) {
                    Date mid = ListaSecCur_EstSec_EntAct.getActividadFechaEntrega();
                    DateFormat miFe = DateFormat.getDateInstance();
                    String miFec = miFe.format(mid);
                    
                    Date mid2 = ListaSecCur_EstSec_EntAct.getActividadFechaPublicacion();
                    DateFormat miFe2 = DateFormat.getDateInstance();
                    String miFec2 = miFe2.format(mid2);
                    
                    Object [] datosFila = {ListaSecCur_EstSec_EntAct.getTipoActividadDescripcion(), ListaSecCur_EstSec_EntAct.getActividadTitulo(), miFec, miFec2, ListaSecCur_EstSec_EntAct.getActividadPunteo(), ListaSecCur_EstSec_EntAct.getActividadFisica(), ListaSecCur_EstSec_EntAct.getActividadVirtual(), "Realizada", ListaSecCur_EstSec_EntAct.EntregaCalificacion, ListaSecCur_EstSec_EntAct.getEntregaId()};
                    miTablaNotas.addRow(datosFila);
                } else {
                    
                    Date mid = ListaSecCur_EstSec_EntAct.getActividadFechaEntrega();
                    DateFormat miFe = DateFormat.getDateInstance();
                    String miFec = miFe.format(mid);
                    
                    Date mid2 = ListaSecCur_EstSec_EntAct.getActividadFechaPublicacion();
                    DateFormat miFe2 = DateFormat.getDateInstance();
                    String miFec2 = miFe2.format(mid2);
                    
                    Object [] datosFila = {ListaSecCur_EstSec_EntAct.getTipoActividadDescripcion(), ListaSecCur_EstSec_EntAct.getActividadTitulo(), ListaSecCur_EstSec_EntAct.getActividadFechaEntrega(), ListaSecCur_EstSec_EntAct.getActividadFechaPublicacion(), ListaSecCur_EstSec_EntAct.getActividadPunteo(), ListaSecCur_EstSec_EntAct.getActividadFisica(), ListaSecCur_EstSec_EntAct.getActividadVirtual(), "No realizada", ListaSecCur_EstSec_EntAct.EntregaCalificacion, ListaSecCur_EstSec_EntAct.getEntregaId()};
                    miTablaNotas.addRow(datosFila);
                }
                
            }
        }
        Double nota = 0.0;
        if (TablaNotas.getRowCount() > 0) {
            for (int i = 0; i < TablaNotas.getRowCount(); i++) {
                nota = nota + Double.parseDouble(TablaNotas.getValueAt(i, 8).toString());
            }
        }
        this.jTextFieldNotaTotal.setText(nota + "");
        
    }

    private void deshabilitarBotones() {
        this.jTextFieldApellido.setEnabled(Boolean.FALSE);
        this.jTextFieldCarne.setEnabled(Boolean.FALSE);
        this.jTextFieldCurso.setEnabled(Boolean.FALSE);
        this.jTextFieldNombre.setEnabled(Boolean.FALSE);
        this.jTextFieldNotaTotal.setEnabled(Boolean.FALSE);
        this.jTextFieldTitulo.setEnabled(Boolean.FALSE);
        this.jTextFieldCalificacion.setEnabled(Boolean.FALSE);
        this.jButtonCalificacion.setEnabled(Boolean.FALSE);
    }

    
    private void esconderColumna() {
        TablaNotas.getColumnModel().getColumn(9).setMaxWidth(0);
        TablaNotas.getColumnModel().getColumn(9).setMinWidth(0);
        TablaNotas.getColumnModel().getColumn(9).setPreferredWidth(0);
    }

    public void tablaNotaSeleccion(JTable tablaNot){
        if (tablaNot.getSelectedRow() != -1) {
            int fila = TablaNotas.getSelectedRow();
            
            
            
            String calificacion = TablaNotas.getValueAt(fila, 8).toString();
            entId = Integer.parseInt(TablaNotas.getValueAt(fila, 9).toString());
            String titulo = TablaNotas.getValueAt(fila, 1).toString();
            this.jTextFieldTitulo.setText(titulo);
            this.jTextFieldCalificacion.setText(calificacion);
            this.jTextFieldCalificacion.setEnabled(Boolean.TRUE);
            this.jButtonCalificacion.setEnabled(Boolean.TRUE);
        }
    }
}
