/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Curso;

import Curso.R_Catedratico;
import Tablas.Archivo;
import Tablas.Recurso;
import java.io.File;
import java.util.Date;
import javax.persistence.Query;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Pablo López
 */
public class CrearRecurso extends javax.swing.JInternalFrame {
    private R_Catedratico rc;
    private File archivoA;
    
    /**
     * Creates new form CrearCurso
     * @param rc
     */
    public CrearRecurso(R_Catedratico rc) {
        initComponents();
        BotonBuscar.setEnabled(Boolean.FALSE);
        jTextField2.setEnabled(Boolean.FALSE);
        setIconifiable(Boolean.TRUE);
        setVisible(Boolean.TRUE);
        setClosable(Boolean.TRUE);
        //setResizable(Boolean.TRUE);
        this.rc=rc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        BotonBuscar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Título");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Descripción");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox1.setText("Archivo");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BotonBuscar.setText("Buscar archivo");
        BotonBuscar.setPreferredSize(new java.awt.Dimension(100, 23));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonCancelar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        BotonAceptar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jCheckBox1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()==true){
            BotonBuscar.setEnabled(Boolean.TRUE);
            jTextField2.setEnabled(Boolean.TRUE);
        }
        else{
            BotonBuscar.setEnabled(Boolean.FALSE);
            jTextField2.setEnabled(Boolean.FALSE);
            archivoA = null;
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int opcion = fc.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION){
            archivoA=fc.getSelectedFile();
            jTextField2.setText(archivoA.getName());
        }
        else{
            archivoA=null;
            jTextField2.setText("");
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun archivo.");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:
        String titulo = jTextField1.getText();
        String descripcion = jTextArea1.getText();
        if (titulo != null && titulo.compareTo("") != 0) {
            if (jCheckBox1.isSelected() == Boolean.TRUE) {
                if (archivoA != null) {
                    int idA = 0;
                    if (jCheckBox1.isSelected() == Boolean.TRUE) {
                        String nombre = archivoA.getName().split("\\.")[0];
                        String extension = archivoA.getName().split("\\.")[archivoA.getName().split("\\.").length - 1];
                        double tamanyo = archivoA.length();
                        Archivo adjunto = new Archivo(0, nombre, extension, "", tamanyo);
                        rc.getControladorA().create(adjunto);
                        Query q;
                        q = rc.getEmf().createEntityManager().createNamedQuery("Archivo.findMaxId");
                        Object maximo = q.getSingleResult();
                        if(maximo!=null){
                            idA=(int)maximo;
                        }
                    }
                    Date fecha = new Date();
                    Recurso rec = new Recurso(0, titulo, descripcion, fecha, idA, rc.getIdSeccionCurso());
                    rc.getControladorR().create(rec);
            JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Recurso creado con exito.</font></html>");
                    this.dispose();
                } else {
            JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Debe seleccionar un archivo para continuar.</font></html>");
                }
            } else {
                Date fecha = new Date();
                Recurso rec = new Recurso(0, titulo, descripcion, fecha, 0, rc.getIdSeccionCurso());
                rc.getControladorR().create(rec);
            JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Recurso creado con exito.</font></html>");
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Debe ponerle un titulo a este recurso.</font></html>");
        }

    }//GEN-LAST:event_BotonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
