/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Curso;

import Controladores.exceptions.NonexistentEntityException;
import Curso.R_Catedratico;
import Tablas.Archivo;
import Tablas.Recurso;
import java.io.File;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo López
 */
public class ModificarRecurso extends javax.swing.JInternalFrame {
    R_Catedratico rc;
    Recurso r;
    Archivo a;
    File archivoA;
    /**
     * Creates new form ModificarRecurso
     * @param rc
     * @param r
     * @param a
     */
    public ModificarRecurso(R_Catedratico rc, Recurso r, Archivo a) {
        initComponents();
        setIconifiable(Boolean.TRUE);
        setVisible(Boolean.TRUE);
        setClosable(Boolean.TRUE);
        //setResizable(Boolean.TRUE);
        this.rc=rc;
        this.r=r;
        this.a=a;
        archivoA=null;
        jTitulo.setText(r.getTitulo());
        jDescripcion.setText(r.getDescripcion());
        if(a!=null){
            jCheckBox1.setSelected(Boolean.TRUE);
            jArchivo.setEnabled(Boolean.TRUE);
            BotonBuscar.setEnabled(Boolean.TRUE);
            jArchivo.setText(a.getNombre()+"."+a.getExtension());
        }
        else{
            jCheckBox1.setSelected(Boolean.FALSE);
            jArchivo.setEnabled(Boolean.FALSE);
            BotonBuscar.setEnabled(Boolean.FALSE);
            jArchivo.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescripcion = new javax.swing.JTextArea();
        jArchivo = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        BotonBuscar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();

        BotonAceptar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BotonAceptar.setText("Aceptar");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Título");

        jTitulo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Descripción");

        jDescripcion.setColumns(20);
        jDescripcion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jDescripcion.setRows(5);
        jScrollPane1.setViewportView(jDescripcion);

        jArchivo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCheckBox1.setText("Archivo");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        BotonBuscar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BotonBuscar.setText("Buscar archivo");
        BotonBuscar.setPreferredSize(new java.awt.Dimension(100, 23));
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonCancelar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jCheckBox1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(BotonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
        // TODO add your handling code here:
        String titulo = jTitulo.getText();
        String descripcion = jDescripcion.getText();
        if (titulo != null && titulo.compareTo("") != 0) {
            int idA=0;
            if(jCheckBox1.isSelected()==Boolean.TRUE){
                if(a!=null||archivoA!=null){
                    if(a!=null){
                        idA=a.getId();
                        if(archivoA!=null){                        
                            a.setNombre(archivoA.getName().split("\\.")[0]);
                            a.setExtension(archivoA.getName().split("\\.")[archivoA.getName().split("\\.").length - 1]);
                            a.setUrl("");
                            a.setTamanio(archivoA.length());
                            try {
                                rc.getControladorA().edit(a);
                            } catch (Exception ex) {
                                Logger.getLogger(ModificarRecurso.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
                    else{
                        idA = rc.getControladorA().getArchivoCount() + 1;
                        String nombre = archivoA.getName().split("\\.")[0];
                        String extension = archivoA.getName().split("\\.")[archivoA.getName().split("\\.").length - 1];
                        double tamanyo = archivoA.length();
                        a = new Archivo(idA, nombre, extension, "", tamanyo);
                        rc.getControladorA().create(a);                        
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Debe seleccionar un archivo para continuar.</font></html>");
                }
            }
            else{
                if(a!=null){
                    try {
                        rc.getControladorA().destroy(a.getId());
                    } catch (NonexistentEntityException ex) {
                        Logger.getLogger(ModificarRecurso.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            r.setArchivoid(idA);
            r.setTitulo(titulo);
            r.setDescripcion(descripcion);
            try {
                rc.getControladorR().edit(r);
            } catch (Exception ex) {
                Logger.getLogger(ModificarRecurso.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Recurso modificado con exito.</font></html>");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "<html><FONT SIZE=4>Debe ponerle un titulo a este recurso.</font></html>");
        }
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()==true){
            BotonBuscar.setEnabled(Boolean.TRUE);
            jArchivo.setEnabled(Boolean.TRUE);
        }
        else{
            BotonBuscar.setEnabled(Boolean.FALSE);
            jArchivo.setEnabled(Boolean.FALSE);
            archivoA = null;
            jArchivo.setText("");
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int opcion = fc.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION){
            archivoA=fc.getSelectedFile();
            jArchivo.setText(archivoA.getName());
        }
        else{
            archivoA=null;
            jArchivo.setText("");
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun archivo.");
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JTextField jArchivo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextArea jDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTitulo;
    // End of variables declaration//GEN-END:variables
}
