/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Curso;

import Curso.CRecurso;
import Curso.ModeloTablaRecurso;
import Curso.R_Catedratico;
import Tablas.Archivo;
import Tablas.Recurso;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo López
 */
public abstract class PrincipalRecurso extends javax.swing.JInternalFrame{

    public CRecurso r;
    /**
     * Creates new form Recursos
     */
    public PrincipalRecurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        botonCrearR = new javax.swing.JButton();
        botonModificarR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRecursos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonVer = new javax.swing.JButton();

        setTitle("Principal recurso");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        botonCrearR.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        botonCrearR.setText("Crear");
        botonCrearR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearRActionPerformed(evt);
            }
        });

        botonModificarR.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        botonModificarR.setText("Modificar");
        botonModificarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarRActionPerformed(evt);
            }
        });

        TablaRecursos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        TablaRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaRecursos.setRowHeight(30);
        jScrollPane1.setViewportView(TablaRecursos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Recursos:");

        botonVer.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        botonVer.setText("Ver");
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonCrearR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonModificarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(botonVer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(botonVer)
                        .addGap(18, 18, 18)
                        .addComponent(botonCrearR)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarR)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        r=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void botonCrearRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearRActionPerformed
        // TODO add your handling code here:
        CrearRecurso rc = new CrearRecurso((R_Catedratico) r);
        this.getParent().add(rc);
        rc.toFront();
    }//GEN-LAST:event_botonCrearRActionPerformed

    private void botonModificarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarRActionPerformed
        // TODO add your handling code here:
        int fila = TablaRecursos.getSelectedRow();
        if (fila >= 0) {
            ModeloTablaRecurso modelo = (ModeloTablaRecurso) TablaRecursos.getModel();
            Date fecha = (Date) modelo.getValueAt(fila, 0);
            String titulo = (String) modelo.getValueAt(fila, 1);
            Query q;
            q = r.getEmf().createEntityManager().createNamedQuery("Recurso.findByFechaPublicacion");
            q.setParameter("fechaPublicacion", fecha);
            List<Recurso> recs = q.getResultList();
            Recurso rec = null;
            for (Recurso rec1 : recs) {
                if (rec1.getTitulo().compareTo(titulo) == 0) {
                    rec = rec1;
                    break;
                }
            }
            q = r.getEmf().createEntityManager().createNamedQuery("Archivo.findById");
            q.setParameter("id", rec.getArchivoid());
            List archivos =  q.getResultList();
            ModificarRecurso mr = new ModificarRecurso((R_Catedratico) r,rec, null);
            if(archivos.size()>0){
                mr = new ModificarRecurso((R_Catedratico) r,rec, (Archivo) archivos.get(0));
            }
            getParent().add(mr);
            mr.toFront();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un recurso.", "", JOptionPane.INFORMATION_MESSAGE);
        }        
    }//GEN-LAST:event_botonModificarRActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        // TODO add your handling code here:
        int fila = TablaRecursos.getSelectedRow();
        if (fila >= 0) {
            ModeloTablaRecurso modelo =  (ModeloTablaRecurso) TablaRecursos.getModel();
            Date fecha = (Date) modelo.getValueAt(fila, 0);
            String titulo = (String) modelo.getValueAt(fila, 1);
            Query q;
            q = r.getEmf().createEntityManager().createNamedQuery("Recurso.findByFechaPublicacion");
            q.setParameter("fechaPublicacion", fecha);
            List<Recurso> recs = q.getResultList();
            Recurso rec = null;
            for (Recurso rec1 : recs) {
                if (rec1.getTitulo().compareTo(titulo) == 0) {
                    rec = rec1;
                    break;
                }
            }
            q = r.getEmf().createEntityManager().createNamedQuery("Archivo.findById");
            q.setParameter("id", rec.getArchivoid());
            List archivos =  q.getResultList();
            VerRecurso vr = new VerRecurso(rec, null);
            if(archivos.size()>0){
                vr = new VerRecurso(rec, (Archivo) archivos.get(0));
            }
            getParent().add(vr);
            vr.toFront();
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un recurso.", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TablaRecursos;
    public javax.swing.JButton botonCrearR;
    public javax.swing.JButton botonModificarR;
    private javax.swing.JButton botonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
