/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Curso;

import Controladores.ArchivoJpaController;
import Controladores.DetalleentregaJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Curso.CCurso;
import Curso.ModeloTablaArchivos;
import Tablas.Archivo;
import Tablas.Detalleentrega;
import Tablas.Entrega;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author modm12
 */
public class R_Entregas extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public R_Entregas(CCurso curso, int idEntrega) {
        initComponents();
        this.curso= curso;
        archivos= new ArrayList<>();
        entrega=curso.getActividad().obtenerEntrega(idEntrega);
        controldetalles=null;
        if(entrega.getRealizada()){
            
        }else{
            
        }
        
        
    }
    public R_Entregas() {
        initComponents();
        archivos= new ArrayList<>();
        
    }
    List<Archivo> archivos;
    List<Detalleentrega> detalle;
    ModeloTablaArchivos modelo;
    DetalleentregaJpaController controldetalles;
    ArchivoJpaController controlarchivo;
    CCurso curso;
    Entrega entrega;
    
    public void obtenerArchivos(){
        detalle=new ArrayList<>();
        Query q;
        EntityManager em=curso.getActividad().getEmf().createEntityManager();
        q=em.createNamedQuery("Detalleentrega.findByEntregaid");
        q.setParameter("entregaid", entrega.getId());
        detalle= q.getResultList();
        
        for(Detalleentrega d:detalle){
            q=em.createNamedQuery("Archivo.findById");
            q.setParameter("id", d.getArchivoid());
            archivos.add((Archivo) q.getSingleResult());
        }
    }
    
    public void eliminar(Archivo arch,int idRow){
        if(arch.getId()>0){
            for(Detalleentrega d:detalle){
                if(d.getArchivoid()==arch.getId()){
                    try {
                        controldetalles.destroy(d.getId());
                    } catch (NonexistentEntityException ex) {
                        Logger.getLogger(R_Entregas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    
                }
            }
            obtenerArchivos();
            modelo= new ModeloTablaArchivos(archivos);
            jTable1.setModel(modelo);
            
        }else{
            archivos.remove(idRow);
            modelo= new ModeloTablaArchivos(archivos);
            jTable1.setModel(modelo);
            
        }
        
        
        
        
    }
    
    private int maxDetalleentregaadId(){
        Query q;
        EntityManager em=curso.getActividad().getEmf().createEntityManager();
        q=em.createNamedQuery("Detalleentrega.findMaxId");;
        return q.getFirstResult();
    }
    private int maxArchivosId(){
        Query q;
        EntityManager em=curso.getActividad().getEmf().createEntityManager();
        q=em.createNamedQuery("Archivo.findMaxId");;
        return q.getFirstResult();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Agregar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar entrega");

        jButton3.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int opcion = fc.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION){
            Archivo arch= new Archivo();
            File file=fc.getSelectedFile();
            String [] st= file.getName().split("\\.");
            
            arch.setNombre(st[0]);
            arch.setTamanio(file.length());
            arch.setExtension(st[1]);
            arch.setUrl(file.getAbsolutePath());
            archivos.add(arch);
            modelo= new ModeloTablaArchivos(archivos);
            jTable1.setModel(modelo);
            }
        else{
            
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun archivo.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
